// Code generated by protoc-gen-go. DO NOT EDIT.
// source: relay/relay.proto

package relay

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NodeState int32

const (
	// UNKNOWN_NODE_STATE indicates that the state of this node is unknown.
	NodeState_UNKNOWN_NODE_STATE NodeState = 0
	// NODE_CONNECTED indicates that we have established a connection
	// to this node. The client can expect to observe flows from this node.
	NodeState_NODE_CONNECTED NodeState = 1
	// NODE_UNAVAILABLE indicates that the connection to this
	// node is currently unavailable. The client can expect to not see any
	// flows from this node until either the connection is re-established or
	// the node is gone.
	NodeState_NODE_UNAVAILABLE NodeState = 2
	// NODE_GONE indicates that a node has been removed from the
	// cluster. No reconnection attempts will be made.
	NodeState_NODE_GONE NodeState = 3
	// NODE_ERROR indicates that a node has reported an error while processing
	// the request. No reconnection attempts will be made.
	NodeState_NODE_ERROR NodeState = 4
)

var NodeState_name = map[int32]string{
	0: "UNKNOWN_NODE_STATE",
	1: "NODE_CONNECTED",
	2: "NODE_UNAVAILABLE",
	3: "NODE_GONE",
	4: "NODE_ERROR",
}

var NodeState_value = map[string]int32{
	"UNKNOWN_NODE_STATE": 0,
	"NODE_CONNECTED":     1,
	"NODE_UNAVAILABLE":   2,
	"NODE_GONE":          3,
	"NODE_ERROR":         4,
}

func (x NodeState) String() string {
	return proto.EnumName(NodeState_name, int32(x))
}

func (NodeState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b6da3b5c0d1535b3, []int{0}
}

// NodeStatusEvent is a message sent by hubble-relay to inform clients about
// the state of a particular node.
type NodeStatusEvent struct {
	// state_change contains the new node state
	StateChange NodeState `protobuf:"varint,1,opt,name=state_change,json=stateChange,proto3,enum=relay.NodeState" json:"state_change,omitempty"`
	// node_name is the list of nodes for which the above state changes applies
	NodeName []string `protobuf:"bytes,2,rep,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	// message is an optional message attached to the state change (e.g. an
	// error message). The message applies to all nodes in node_name.
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeStatusEvent) Reset()         { *m = NodeStatusEvent{} }
func (m *NodeStatusEvent) String() string { return proto.CompactTextString(m) }
func (*NodeStatusEvent) ProtoMessage()    {}
func (*NodeStatusEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6da3b5c0d1535b3, []int{0}
}

func (m *NodeStatusEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeStatusEvent.Unmarshal(m, b)
}
func (m *NodeStatusEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeStatusEvent.Marshal(b, m, deterministic)
}
func (m *NodeStatusEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeStatusEvent.Merge(m, src)
}
func (m *NodeStatusEvent) XXX_Size() int {
	return xxx_messageInfo_NodeStatusEvent.Size(m)
}
func (m *NodeStatusEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeStatusEvent.DiscardUnknown(m)
}

var xxx_messageInfo_NodeStatusEvent proto.InternalMessageInfo

func (m *NodeStatusEvent) GetStateChange() NodeState {
	if m != nil {
		return m.StateChange
	}
	return NodeState_UNKNOWN_NODE_STATE
}

func (m *NodeStatusEvent) GetNodeName() []string {
	if m != nil {
		return m.NodeName
	}
	return nil
}

func (m *NodeStatusEvent) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("relay.NodeState", NodeState_name, NodeState_value)
	proto.RegisterType((*NodeStatusEvent)(nil), "relay.NodeStatusEvent")
}

func init() { proto.RegisterFile("relay/relay.proto", fileDescriptor_b6da3b5c0d1535b3) }

var fileDescriptor_b6da3b5c0d1535b3 = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8f, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x40, 0x4d, 0xe3, 0xd7, 0x8e, 0x1a, 0xd7, 0x41, 0x24, 0xe0, 0x25, 0x78, 0x0a, 0x1e, 0x2a,
	0xd8, 0x5f, 0x10, 0xd3, 0x45, 0xc4, 0x32, 0x0b, 0xdb, 0x54, 0x8f, 0x61, 0xb5, 0x43, 0x3d, 0x34,
	0x89, 0x74, 0x57, 0xc1, 0x83, 0xff, 0x5d, 0x1c, 0xa9, 0x97, 0x81, 0xf7, 0x78, 0x33, 0x30, 0x70,
	0xb6, 0xe1, 0xb5, 0xff, 0xba, 0x91, 0x39, 0x7e, 0xdf, 0x0c, 0x71, 0xc0, 0x3d, 0x81, 0xab, 0x6f,
	0x38, 0xa5, 0x61, 0xc9, 0xf3, 0xe8, 0xe3, 0x47, 0x30, 0x9f, 0xdc, 0x47, 0x9c, 0xc0, 0x71, 0x88,
	0x3e, 0x72, 0xfb, 0xfa, 0xe6, 0xfb, 0x15, 0xe7, 0x49, 0x91, 0x94, 0xd9, 0xad, 0x1e, 0xff, 0x6d,
	0x6f, 0x6b, 0x76, 0x47, 0x52, 0xd5, 0x12, 0xe1, 0x25, 0xa8, 0x7e, 0x58, 0x72, 0xdb, 0xfb, 0x8e,
	0xf3, 0x51, 0x91, 0x96, 0xca, 0x1d, 0xfe, 0x0a, 0xf2, 0x1d, 0x63, 0x0e, 0x07, 0x1d, 0x87, 0xe0,
	0x57, 0x9c, 0xa7, 0x45, 0x52, 0x2a, 0xb7, 0xc5, 0xeb, 0x35, 0xa8, 0xff, 0x83, 0x78, 0x01, 0xb8,
	0xa0, 0x47, 0xb2, 0xcf, 0xd4, 0x92, 0x9d, 0x9a, 0x76, 0xde, 0x54, 0x8d, 0xd1, 0x3b, 0x88, 0x90,
	0x09, 0xd7, 0x96, 0xc8, 0xd4, 0x8d, 0x99, 0xea, 0x04, 0xcf, 0x41, 0x8b, 0x5b, 0x50, 0xf5, 0x54,
	0x3d, 0xcc, 0xaa, 0xbb, 0x99, 0xd1, 0x23, 0x3c, 0x01, 0x25, 0xf6, 0xde, 0x92, 0xd1, 0x29, 0x66,
	0x00, 0x82, 0xc6, 0x39, 0xeb, 0xf4, 0xee, 0xcb, 0xbe, 0xbc, 0x3e, 0xf9, 0x09, 0x00, 0x00, 0xff,
	0xff, 0xde, 0xa5, 0x9f, 0xa5, 0x0f, 0x01, 0x00, 0x00,
}
